# Travis configuration file
# http://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.5"

# Install fits_reduce...
install:
  - pip install .
  - pip install coveralls
# Run tests
script:
  - nosetests --with-coverage --cover-package=a_star --cover-inclusive
after_success:
  - coveralls
